#!/bin/bash -e
#
# Programmatically build unit files. See `test` for example usage.

if [[ $1 == start ]]; then
    workdir=$(mktemp -d gen/build-XXXXXX)
    mkdir -p $workdir/{exec/out,input}
    touch $workdir/{after,copy,set}
    echo $workdir
    exit
fi

if [[ $1 != --build ]]; then
    echo specify start or --build >&2
    exit 1
fi
workdir="$2"
shift; shift

subcommand="$1"
shift

case $subcommand in
    start)
        echo do not use --build with start >&2
        exit 1
        ;;
    copy)
        src="${1?}"
        name="${2?}"
        # /dev/stdin misbehaves in rootless podman.
        # https://github.com/containers/libpod/issues/6659
        if [[ $src == /dev/stdin ]]; then
            cat > "$workdir/input/$name"
        else
            cp "$src" "$workdir/input/$name"
        fi
        echo "$name" >> "$workdir/copy"
        echo "$src available as \$input_$name" >&2
        ;;
    set)
        name="${1?}"
        value="${2?}"
        echo "$value" > "$workdir/input/$name"
        echo "in/$name=inline:$value" >> "$workdir/set"
        echo "\"$value\" file contents available as in/$name" >&2
        ;;
    after)
        unit="${1?}"
        path="${2?}"
        name="${3?}"
        invocation=$(./run-flow "$unit")
        ./show-output $invocation $path > "$workdir/input/$name"
        echo "$name $unit $path" >> "$workdir/after"
        echo "output of $unit available as in/$name" >&2
        ;;
    run)
        cmd="${1?}"
        cp -R "$workdir"/input "$workdir"/exec/in
        echo "$cmd" >> "$workdir/run"
        cd "$workdir/exec"
        eval $cmd
        ;;
    commit)
        unit="${1?}"
        mkdir -p "$unit.d"
        if [[ $(wc -l < "$workdir/run") -le 1 ]]; then # single line command
            echo "process=command:$(<"$workdir/run")" > "$unit"
        else # multi-line command
            cp "$workdir/run" "$unit.d/run"
            echo 'process=command:bash -e in/run' > "$unit"
            echo "in/run=file:$unit.d/run" >> "$unit"
        fi
        while read name; do
            cp "$workdir/input/$name" "$unit.d/$name"
            echo "in/$name=file:$unit.d/$name" >> "$unit"
        done < "$workdir/copy"
        while read name dep path; do
            echo "in/$name=unit:$dep:$path" >> "$unit"
        done < "$workdir/after"
        cat "$workdir/set" >> "$unit"
        # TODO sort unit?
        rmdir "$unit.d" &> /dev/null || true # remove if empty
        rm -rf "$workdir"
        echo "Wrote $unit" >&2
        ;;
    discard)
        rm -r "$workdir"
        ;;
    help)
        echo '  start' >&2
        echo '  --build [build] copy [src] [name]' >&2
        echo '  --build [build] after [unit] [name]' >&2
        echo '  --build [build] run [command]' >&2
        echo '  --build [build] commit [unit]' >&2
        exit 1
        ;;
    *)
        echo "unknown command $subcommand" >&2
        echo >&2
        exec "$0" help
        ;;
esac
