#!/bin/bash -e
#
# Check that a plan has a valid terminal.

plan=$1
terminal_pos=$2

alldeps() {
    while read -r pos; do
        echo $pos
        ./extract-step $plan $pos | grep ^in/ | cut -d= -f2 | grep ^_pos: | cut -d: -f2 | sort -u | alldeps
    done | sort -u
}

if ! diff <(echo $terminal_pos | alldeps) <(grep ^_pos= $plan | cut -d= -f2 | sort -u) >&2; then
    echo $terminal_pos is not the terminal of $plan >&2
    exit 1
fi
