#!/bin/bash -e

[[ $# -eq 1 ]]
plan="$1"

# TODO hardcoded session directory

dir=$(mktemp -d)
mkdir -p $dir/{inputs,awaiting}/{a,b,c}
mkdir $dir/{resolved,productions}

echo 'mkdir out/result.d && seq 1 3 > out/result.d/data && false' > $dir/inputs/a/shell

echo 'cp -RL in/input.d out/result.d' > $dir/inputs/b/shell
ln -s ../../productions/a $dir/awaiting/b/a
ln -s ../../productions/a/.knit/ok.d $dir/inputs/b/a.ok.d
ln -s ../../productions/a/result.d $dir/inputs/b/input.d

echo 'mkdir out/result.d && tac in/lines.d/data > out/result.d/data' > $dir/inputs/c/shell
ln -s ../../productions/b $dir/awaiting/c/b
ln -s ../../productions/b/.knit/ok.d $dir/inputs/c/b.ok.d
ln -s ../../productions/b/result.d $dir/inputs/c/lines.d

echo $dir
