#!/bin/bash -e

[[ $# -eq 1 ]]
plan="$1"

# TODO hardcoded session directory

dir=$(mktemp -d)
mkdir -p $dir/inputs/{a,b}
mkdir $dir/{resolved,productions}

echo 'mkdir out/result.d && seq 1 3 > out/result.d/data' > $dir/inputs/a/shell

echo 'mkdir out/result.d && tac in/lines.d/data > out/result.d/data' > $dir/inputs/b/shell
ln -s ../../productions/a/.knit/ok.d $dir/inputs/b/a.ok.d
ln -s ../../productions/a/result.d $dir/inputs/b/lines.d

echo $dir
