#!/usr/bin/perl -w
#
# Compatibility layer to translate a tree into an execution plan.

use strict;
use v5.14;

my ($root) = @ARGV;

my %treepos;
my $pos = 0;
sub flatten {
    my ($tree) = @_;
    unless (exists $treepos{$tree}) {
        my @lines = split "\n", `./kgit cat-file blob $tree`;
        unshift @lines, "_tree=$tree";
        unshift @lines, "_pos=$pos";
        $treepos{$tree} = $pos++;
        for (@lines) {
            s/^output=/_$&/;
            s/^input_[^=]+=\Ktree:(.*)$/'_pos:' . flatten($1)/e;
        }
        say for (@lines);
        say '';
    }
    return $treepos{$tree};
}

flatten $root;
