#!/bin/bash -e

if [[ -z $graph_recursive ]]; then
    # accept an invocation instead
    if [[ $# -eq 1 ]]; then
        while IFS== read -r key value; do
            if [[ $key = production || $key = partial_production:* ]]; then
                set -- $@ $value
            fi
        done < <(./kgit cat-file blob $1)
        # if we pushed any productions, remove the invocation
        [[ $# -gt 1 ]] && shift || true
    fi

    # strict simplifies duplicate outputs.
    echo strict digraph G {
    echo 'rankdir=BT;'
    echo 'node [shape=box,style=filled,fillcolor=white];'
    for production in $@; do
        graph_recursive=1 ./graph-production $production
    done
    echo }
    exit
fi

production=$1

plot_resource() {
    [[ -n $graphresources ]] || return 0
    production=$1
    path=$2
    dir=$3
    blob=$4
    if [[ $dir = to ]]; then
        echo "\"$production\" -> \"$blob\" [tooltip=\"$path\"];"
    else
        echo "\"$blob\" -> \"$production\" [tooltip=\"$path\"];"
    fi
    echo "\"$blob\" [label=\" \",tooltip=\"$blob\",shape=note];"
}

while IFS== read -r key value; do
    case $key in
        # cache is not shown; decide how to make it useful
        _source|start_ts|end_ts|exit_code|cache) declare $key="$value" ;;
        dep:*)
            ./graph-production $value
            echo "\"$value\" -> \"$production\";"
            ;;
        invocation)
            ./kgit cat-file blob $value | grep -e ^production= -e ^partial_production: | cut -d= -f2 | while read subproduction; do
                echo subgraph cluster_$subproduction {
                ./graph-production $subproduction
                echo }
                echo "\"$subproduction\" -> \"$production\";"
            done
            ;;
        job)
            while IFS== read -r key value; do
                case $key in
                    process) declare $key="$value" ;;
                    in/*|inref/*) plot_resource $production $key from $value ;;
                    *) echo Unknown job key $key >&2 ;;
                esac
            done < <(./kgit cat-file blob $value)
            ;;
        out/*)
            plot_resource $production $key to $value
            ;;
        *) echo Unknown production key $key >&2 ;;
    esac
done < <(./kgit cat-file blob $production)
duration=N/A
if [[ -n $start_ts && -n $end_ts ]]; then
    duration=$(( $(date -d $end_ts +%s) - $(date -d $start_ts +%s) ))
fi
echo "\"$production\" [label=\"$_source\",tooltip=\"$process\n${duration}s $exit_code\",URL=\"http://localhost:8000/cgi-bin/inspect/production/$production\"];"
