#!/bin/bash -e
#
# Get the production roots of an execution plan. These are the roots of all
# executed productions. They are also the steps closest to the plan frontier. For
# a successfully completed plan it should be a single terminal.
#
# This exhibits a caching issue. Say A -> B. If A changes to A' but has the same
# outputs, job caching will reuse B. However B will still reference the
# production of A. This will then return both A' and B as roots. If we drop A'
# as a root, our invocation would not include its actual production.

plan=$1

grep ^_production= $plan | cut -d= -f2 | sort -u > gen/roots.$$

while read -r production; do
    ./kgit cat-file blob $production | grep ^dep: | cut -d= -f2 > gen/deps.$$
    # BSD grep fails if -f file is empty.
    if [[ -s gen/deps.$$ ]]; then
        grep -Fxvf gen/deps.$$ gen/roots.$$ > gen/roots.$$.tmp
        mv gen/roots.$$.tmp gen/roots.$$
    fi
done < gen/roots.$$

cat gen/roots.$$

rm -f gen/deps.$$ gen/roots.$$
