#!/usr/bin/python3

import subprocess
import sys

# TODO DRY with main implementation in build-plan

for line in sys.stdin:
    line = line.strip()
    if '=' in line:
        key, value = line.split('=', 1)
        if key.startswith('in/'):
            if value.startswith('file:'):
                cid = subprocess.check_output(f'./kgit hash-object -w --stdin < "{value[5:]}"', shell=True, text=True).strip()
                line = f'{key}={cid}'
    print(line)
