#!/bin/bash -e
#
# Run an execution plan.

plan=$1

set -o pipefail

initial_plan=$(./kgit hash-object -w --stdin < $plan)
./schedule-step $plan > gen/next
while true; do
    [[ $(wc -l < gen/next) -eq 0 ]] && break
    # TODO allow manual jobs
    pos=$(head -n1 gen/next)

    ./extract-step $plan $pos > gen/step
    source=$(grep ^_source= gen/step | cut -d= -f2) || true
    # Convert step to job.
    grep -v ^_ gen/step > gen/job
    # TODO more nuanced caching policy
    job=$(./kgit hash-object -w --stdin < gen/job)

    # TODO dispatch interface to schedule-step is awkward
    echo -e "_pos=$pos\njob=$job" > gen/dispatch.$$
    if dispatch=$(./kgit rev-parse --verify -q refs/job/$job/lastdispatch); then
        ./kgit cat-file blob $dispatch | grep ^out/ >> gen/dispatch.$$ || true
        echo _dispatch=$dispatch >> gen/dispatch.$$
        ./schedule-step $plan gen/dispatch.$$ > gen/next
    else
        echo Running job:$job $source >&2
        ./run-job < gen/job >> gen/dispatch.$$
        ./schedule-step $plan gen/dispatch.$$ > gen/next
        dispatch=$(./extract-step $plan $pos | grep ^_dispatch= | cut -d= -f2)
        ./kgit update-ref refs/job/$job/lastdispatch $dispatch
    fi

    ./kgit update-ref refs/lastdispatch $dispatch
done

rm gen/dispatch.$$

./kgit hash-object -w --stdin <<EOF
_annotated_plan=$(./kgit hash-object -w --stdin < $plan)
dispatch=$dispatch
plan=$initial_plan
EOF
