#!/bin/bash -e
#
# Run a target unit file and its dependencies.

if [[ -n $RUN_PORTABLE ]]; then
    if [[ $1 = flow/* ]]; then
        exec ./run-portable flow/ "$@"
    else
        echo warn: downgrading to run-flow for flow outside of flow/ >&2
    fi
fi

exec cargo run -q run-unit "$@"
