#!/bin/bash -e

target=$1
shift

# map params to in/param
set -- $(echo "$@" | sed -E 's:(^| )in/:\1in/param/:g')

ktroot=$(dirname $target)
while [[ ! -e $ktroot/_ktroot ]]; do
    if [[ ${#ktroot} -eq 1 ]]; then
        echo 'no _ktroot found' >&2
        exit 1
    fi
    ktroot=$(dirname $ktroot)
done

if ! invocation=$(./run-flow flow/template/pipeline.unit in/raw/=file:$ktroot/ in/targets=inline:${target#$ktroot/} "$@"); then
    echo $invocation
    exit 1
fi

# materialize outputs
rm -rf gen/out
./materialize-outputs $invocation gen

echo $invocation
echo outputs in gen/out/ >&2
