#!/bin/bash -e

for target in $@; do
    # find _ktroot from first argument
    if [[ -z $ktroot ]]; then
        ktroot=$(dirname $target)
        while [[ ! -e $ktroot/_ktroot ]]; do
            if [[ ${#ktroot} -eq 1 ]]; then
                echo 'no _ktroot found' >&2
                exit 1
            fi
            ktroot=$(dirname $ktroot)
        done
    fi
    if [[ $target != $ktroot/* ]]; then
        echo 'targets have different _ktroot?' >&2
        exit 1
    fi
    echo ${target#$ktroot/}
done > >(sort > gen/targets)  # avoid subshelling loop

if ! invocation=$(./run-flow flow/template/pipeline.unit in/raw/=file:$ktroot/ in/targets=file:gen/targets); then
    echo $invocation
    exit 1
fi

# materialize outputs
rm -rf gen/out
./materialize-outputs $invocation gen

echo $invocation
echo outputs in gen/out/ >&2
