#!/bin/bash -e
#
# Run an execution plan.

plan=$1

set -o pipefail

./schedule-step $plan > gen/next
while true; do
    [[ $(wc -l < gen/next) -eq 0 ]] && break
    # TODO allow manual jobs
    pos=$(head -n1 gen/next)

    ./extract-step $plan $pos > gen/step
    source=$(grep ^_source= gen/step | cut -d= -f2) || true
    # Convert step to job.
    grep -v ^_ gen/step > gen/job
    # TODO more nuanced caching policy
    job=$(./kgit hash-object -w --stdin < gen/job)

    # TODO invocation interface to schedule-step is awkward
    echo -e "_pos=$pos\njob=$job" > gen/invocation.$$
    if invocation=$(./kgit rev-parse --verify -q refs/job/$job/lastinvocation); then
        ./kgit cat-file blob $invocation | grep ^out/ >> gen/invocation.$$ || true
        echo _invocation=$invocation >> gen/invocation.$$
        ./schedule-step $plan gen/invocation.$$ > gen/next
    else
        echo Running job:$job $source >&2
        ./run-job < gen/job >> gen/invocation.$$
        ./schedule-step $plan gen/invocation.$$ > gen/next
        invocation=$(./extract-step $plan $pos | grep ^_invocation= | cut -d= -f2)
        ./kgit update-ref refs/job/$job/lastinvocation $invocation
    fi

    ./kgit update-ref refs/lastinvocation $invocation
done

rm gen/invocation.$$

echo $invocation
