#!/bin/bash -e
#
# Run a single job.

workdir=$(mktemp -d gen/job-XXXXXX)

cat > $workdir/job

if grep -qxF process=identity $workdir/job; then
    grep ^in/ $workdir/job | sed -e 's:^in/:out/:'
    echo exit_code=0
    rm -rf $workdir
    exit
fi

while IFS== read -r key value; do
    if [[ $key = in/* ]]; then
        mkdir -p "$(dirname "$workdir/$key")"
        ./kgit cat-file blob $value > "$workdir/$key"
    elif [[ $key = inref/* ]]; then
        mkdir -p "$(dirname "$workdir/$key")"
        echo $value > "$workdir/$key"
    elif [[ $key = process ]]; then
        IFS=: read -r process_type process_data <<< "$value"
    else
        echo Unknown job key "$key" >&2
        exit 1
    fi
done < $workdir/job

echo start_ts=$(date +%FT%T%z)
if [[ $process_type = command ]]; then
    if [[ -d $workdir/inref ]]; then
        echo 'warning: inref used in command process' >&2
    fi
    mkdir $workdir/out
    exit_code=0
    (IFS=$'\n'; cd $workdir; env $(<job) bash -c "$process_data") > $workdir/log || exit_code=$?
    echo exit_code=$exit_code
    find $workdir/out -type f | sort | while read -r path; do
        cid=$(./kgit hash-object -w --stdin < "$path")
        echo "${path#$workdir/}=$cid"
    done
elif [[ $process_type = nested ]]; then
    # Nested flows don't really need parameterization because the command can
    # wire inputs as parameters. But it's natural to consider if params should
    # be exposed in some consistent way here.
    mkdir $workdir/steps
    if (IFS=$'\n'; cd $workdir; env $(<job) bash -c "$process_data") > $workdir/log; then
        find $workdir/steps -type f | sort | while read -r path; do
            echo _pos=${path#$workdir/steps/}
            echo _source=nested:_pos:${path#$workdir/steps/}
            # Kludge for relative file: resources for nested flows.
            sed -e "s@^\\(in/[^=]*=file:\\)\.\\(/.*\\)@\\1$workdir\\2@" $path
            echo
        done > $workdir/plan.$$
        ./resolve-input < $workdir/plan.$$ > $workdir/plan
        # all is hardcoded as the nested flow terminal pos.
        ./check-plan $workdir/plan all
        if invocation=$(./run-plan $workdir/plan); then
            echo exit_code=0
        else
            # This is ambiguous with a failure in the nested process.
            echo exit_code=1
        fi
        production=$(./kgit cat-file blob $invocation | grep ^production= | cut -d= -f2)
        echo invocation=$invocation
        ./kgit cat-file blob $production | grep ^out/
    else
        echo exit_code=$?
    fi
else
    echo Unknown process "$process" >&2
    exit 1
fi
if [[ -s $workdir/log ]]; then
    # Consider how to save logs with storage system.
    log=$(./kgit hash-object -w --stdin < $workdir/log)
    echo log=$log
fi
echo end_ts=$(date +%FT%T%z)

rm -rf $workdir
