#!/bin/bash -e
#
# Run a target unit file and its dependencies.

unit="$1"
shift

echo process=identity > gen/param.unit
for paramline in "$@"; do
    echo "$paramline"
done >> gen/param.unit
./unit-to-plan _param gen/param.unit > gen/plan

./unit-to-plan main "$unit" >> gen/plan
# TODO should prune plan, like unused _param
./run-plan gen/plan
