#!/bin/bash -e

[[ $# -eq 1 ]]
# TODO session directory
sessiondir="$(<$1)"

check_inputs() {
    for input in "$1/"*; do
        [[ -e $input ]] || return 1
    done
}

for step in $(cd "$sessiondir/inputs" && echo *); do
    if [[ ! -e "$sessiondir/resolved/$step" ]] && check_inputs "$sessiondir/inputs/$step"; then
        echo $step
    fi
done
