#!/usr/bin/python3
#
# Find the next steps to run in the current execution plan.

import os
import subprocess
import sys
from datetime import datetime

steps = {}

class Step(object):
    def __init__(self, lines):
        self.stmt = dict(l.split('=', 1) for l in lines)
        # Global magic
        steps[self.stmt['_pos']] = self

    @property
    def completion(self):
        return self.stmt.get('_completion')

    @staticmethod
    def _make_completion(completion):
        with open('gen/completion', 'w') as fh:
            for key, value in sorted(completion.items()):
                print(f'{key}={value}', file=fh)
        return subprocess.check_output('./kgit hash-object -w --stdin < gen/completion', shell=True, text=True).strip()

    def mark_complete(self, completion):
        self.stmt.update({k: v for k, v in completion.items() if k.startswith('out/')})
        cached_completion = completion.pop('_completion', None)
        # TODO this seems awkward
        if cached_completion:
            self.stmt['_completion'] = cached_completion
        else:
            for key, value in self.stmt.items():
                if key.startswith('_dep:') or key == '_source':
                    completion[key[1:]] = value
            if 'source' not in completion:
                completion['source'] = '_pos:' + self.stmt['_pos']
            self.stmt['_completion'] = self._make_completion(completion)

    def resolve_dependencies(self):
        """Build resources from input job dependencies"""
        depkeys = [k for k in self.stmt
                   if k.startswith('in/') or k.startswith('inref/')]
        # Unexecuted dependencies?
        depvalues = [self.stmt[k].split(':') for k in depkeys]
        if not all(steps[v[1]].completion for v in depvalues if v[0] == '_pos'):
            return False
        for inpath in depkeys:
            value = self.stmt[inpath]
            if value.startswith('_pos:'):
                _, pos, outpath = value.split(':', 2)
                self.stmt[f'_dep:{inpath}'] = steps[pos].stmt['_completion']
                assert outpath.startswith('out/')
                if inpath.endswith('/') and outpath.endswith('/'):
                    del self.stmt[inpath]
                    # Map dependency outpath to inpath.
                    self.stmt.update({inpath + k[len(outpath):]: v
                                      for k, v in steps[pos].stmt.items()
                                      if k.startswith(outpath)})
                else:
                    self.stmt[inpath] = steps[pos].stmt[outpath]
        return True

    def save(self, fh):
        for key, value in sorted(self.stmt.items()):
            print(f'{key}={value}', file=fh)
        print(file=fh)

path = sys.argv[1]
lines = []
with open(path) as fh:
    for line in fh:
        line = line.rstrip('\n')
        if line:
            lines.append(line)
        else:
            Step(lines)
            lines = []
if lines:
    Step(lines)

# Optionally mark completed job.
if len(sys.argv) > 2:
    completion_path, = sys.argv[2:]
    with open(completion_path) as fh:
        completion = dict(line.rstrip('\n').split('=', 1) for line in fh)
    if completion:
        pos = completion.pop('_pos')
        steps[pos].mark_complete(completion)

tmp_path = f'{path}.{os.getpid()}'
with open(tmp_path, 'w') as fh:
    for pos, step in sorted(steps.items()):
        if not step.completion and step.resolve_dependencies():
            print(pos)
        step.save(fh)
os.rename(tmp_path, path)
