#!/bin/bash -e
#
# Show output from dispatch or invocation.

dispatch_or_invocation=$1
path=$2

dispatch=$(./kgit cat-file blob $dispatch_or_invocation | grep ^dispatch= | cut -d= -f2)
if [[ -z $dispatch ]]; then
    dispatch=$dispatch_or_invocation
fi

cid=$(./kgit cat-file blob $dispatch | grep "^$path=" | cut -d= -f2)
./kgit cat-file blob $cid
