#!/bin/bash -e
#
# Show output from production or invocation.

production_or_invocation=$1
path=$2

production=$(./kgit cat-file blob $production_or_invocation | grep ^production= | cut -d= -f2)
if [[ -z $production ]]; then
    production=$production_or_invocation
fi

cid=$(./kgit cat-file blob $production | grep "^$path=" | cut -d= -f2)
./kgit cat-file blob $cid
