#!/bin/bash -e

if [[ -d gen/repo/.git/refs/job/ ]]; then
    mv gen/repo/.git/refs/job/ gen/jobcache.$$
    trap "rm -rf gen/repo/.git/refs/job && mv gen/jobcache.$$ gen/repo/.git/refs/job" EXIT
fi

header() {
    echo -e "\n\033[32m$@\033[0m"
}

for test in ./t/*; do
    header $test
    $test
done

set +x
header PASS
