#!/usr/bin/python3
#
# Recursively convert unit file and dependencies to execution plan.

import subprocess
import sys

pos = 0

def translate(unit, appendsuffix=True):
    global pos
    process = None
    inputs = []
    with open(unit) as fh:
        for line in fh:
            if line.startswith('#') or line.isspace():
                continue
            key, value = line.rstrip().split('=', 1)
            if key == 'process':
                process = value
            elif key.startswith('in/') or key.startswith('inref/'):
                if value.startswith('unit:'):
                    _, unit_path, artifact_path = value.split(':', 2)
                    dep = translate(unit_path)
                    value = f'_pos:{dep}:{artifact_path}'
                elif value.startswith('_pos:'):
                    print(f'warning: passing through _pos input in {unit}',
                          file=sys.stderr)
                inputs += [f'{key}={value}\n']
            else:
                raise Exception('unsupported key', key)

    mypos = f'{root_pos}@{pos}' if appendsuffix else root_pos
    subprocess.run(['./build-plan', '--build', build, 'step',
                    mypos, f'unit:{unit}', process],
                   input=''.join(inputs), text=True, check=True)
    pos += 1
    return mypos

_, root_pos, unit = sys.argv
build = subprocess.check_output(['./build-plan', 'start'], text=True).rstrip('\n')
translate(unit, appendsuffix=False)
subprocess.run(['./build-plan', '--build', build, 'commit'], check=True)
