#!/usr/bin/python3
#
# Translate template to plan.

import os
import re
import shutil
import subprocess
import sys


_, source_root, action_root, out_root, out_dir, target, *params = sys.argv


def create(path, mode):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return open(path, mode)


visited = set()
plan = sys.stdout

# write params
if params:
    print('_pos=_param', file=plan)
    print('process=identity', file=plan)
    for param in params:
        print(param, file=plan)
    print(file=plan)
    visited.add('_param')

frontier = [target]
while frontier:
    target = frontier.pop()
    if target in visited:
        continue
    extension = target.rsplit('.', 1)[-1]

    # convert source to reqs and build
    converter = f'{action_root}/converters/{extension}'
    if not os.access(converter, os.X_OK):
        # TODO hardcoded /tmp
        shutil.copy(converter, '/tmp/converter')
        converter = '/tmp/converter'
        os.chmod(converter, 0o755)
    output = subprocess.check_output(f'{converter} {source_root}/{target}', shell=True)
    is_plan = False
    # delimited by blank line
    if output.startswith(b'\n'):
        reqs = []
        build = output[1:]
    else:
        reqs, build = output.split(b'\n\n', 1)
        reqs = reqs.decode('utf-8').split('\n')
        if reqs[0] == 'plan':
            is_plan = True
            del reqs[0]

    # write the step and build
    visited.add(target)
    with create(f'{out_root}/{out_dir}/builds/{target}', 'wb') as fh:
        fh.write(build)
    print(f'_pos={target}', file=plan)
    file_root = '' if out_dir == '.' else f'{out_dir}/'
    if is_plan:
        print('process=dynamic', file=plan)
        print(f'in/plan=file:{file_root}builds/{target}', file=plan)
    else:
        # TODO remove stdout if empty
        print('process=command:chmod +x in/driver && '
              'in/driver in/build > out/-', file=plan)
        # awkward generalized driver copying
        driver = f'{out_root}/{out_dir}/drivers/{extension}'
        os.makedirs(os.path.dirname(driver), exist_ok=True)
        shutil.copy(f'{action_root}/drivers/{extension}', driver)
        print(f'in/driver=file:{file_root}drivers/{extension}', file=plan)
        print(f'in/build=file:{file_root}builds/{target}', file=plan)
    for req in reqs:
        print(req, file=plan)
        match = re.fullmatch(r'in/[^=]*=_pos:([^:]*):.*', req)
        if match:
            frontier.append(match[1])
    print(file=plan)

# copy outputs to main
print('_pos=main', file=plan)
print('process=identity', file=plan)
for step in visited:
    print(f'in/{step}/=_pos:{step}:out/', file=plan)
print(file=plan)
