#!/usr/bin/python3
#
# Browse object store.

import os
import subprocess
import sys

_, objtype, objid = os.environ['PATH_INFO'].split('/')

output = subprocess.check_output(['./kgit', 'cat-file', 'blob', objid], text=True)
if objtype == 'resource':
    print('Content-Type: text/plain')
    print()
    print(output)
    sys.exit()
attrs = dict(line.split('=', 1) for line in output.splitlines())

print('Content-Type: text/html')
print()

print(f'<h1>{objtype}</h1>')
print(f'<h2>{objid}</h2>')

for key, value in attrs.items():
    value_type = None
    if objtype == 'invocation':
        if key == 'plan':
            value_type = 'resource'
        elif key == 'production' or key.startswith('partial_production:'):
            value_type = 'production'
    elif objtype == 'production':
        if key.startswith('dep:') or key == 'cache':
            value_type = 'production'
        elif key == 'invocation':
            value_type = 'invocation'
        elif key == 'job':
            value_type = 'job'
        elif key.startswith('out/'):
            value_type = 'resource'
    elif objtype == 'job':
        if key.startswith('in/') or key.startswith('inref/'):
            value_type = 'resource'

    if value_type is not None:
        value = f'<a href=/cgi-bin/inspect/{value_type}/{value}>{value}</a>'
    print(f'<dt>{key}</dt><dd>{value}</dd>')
