#!/bin/bash -ex

! invocation=$(./run-flow flow/fail/baddep.unit)
partial_production=$(./kgit cat-file blob $invocation | grep ^partial_production:)
! invocation=$(./run-flow flow/fail/error.unit)
[[ $partial_production == $(./kgit cat-file blob $invocation | grep ^partial_production:) ]]
