#!/bin/bash -ex

invocation=$(./run-flow flow/param/ab.unit in/x=inline:x in/y=inline:y)
diff - <(./show-output $invocation out/_) <<EOF
a1
x
y
EOF

invocation=$(./run-flow flow/param/dir.unit in/dir/=file:flow/param/dir.d/)
diff - <(./show-output $invocation out/_) <<EOF
dir.d/c
EOF
