#!/bin/bash -ex

invocation=$(./run-template flow/template/inputs.d/tac.py)
diff - gen/out/abc.sh/- <<EOF
a
b
c
EOF
diff - gen/out/tac.py/- <<EOF
c
b
a
EOF

invocation=$(./run-template flow/template/inputs.d)
diff - gen/out/recombine.py/- <<EOF
name,sum(score),letter
charlie,10,c
bob,8,b
alice,3,a
EOF

invocation=$(./run-template flow/template/inputs.d/param.sh in/a=inline:x)
diff - gen/out/param.sh/- <<EOF
x
EOF
