#!/bin/bash -ex

invocation=$(./run-template flow/template/inputs.d/tac.py)
diff - gen/out/abc.sh/- <<EOF
a
b
c
EOF
diff - gen/out/tac.py/- <<EOF
c
b
a
EOF

invocation=$(./run-template flow/template/inputs.d)
diff - gen/out/recombine.py/- <<EOF
name,sum(score),letter
charlie,10,c
bob,8,b
alice,3,a
EOF

invocation=$(./run-template flow/template/inputs.d/param.sh in/a=inline:x in/dir/=file:flow/template/inputs.d/dir/)
diff - gen/out/param.sh/- <<EOF
x
dir/file
EOF

invocation=$(./run-flow flow/template/nested.unit)
diff - <(./show-output $invocation out/nested.sh/-) <<EOF
x
dir/file
dir/file
EOF
